version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo installing dependencies
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login -u AWS --password-stdin 673593240843.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo "build microservices"
      - cd claimservice
      - mvn package
      - docker build -t $CLAIM_IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $CLAIM_IMAGE_REPO_NAME:$IMAGE_TAG $CLAIM_ECR_URL:$IMAGE_TAG
      - cd ..
      - cd policyservice
      - mvn package
      - docker build -t $POLICY_IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $POLICY_IMAGE_REPO_NAME:$IMAGE_TAG $POLICY_ECR_URL:$IMAGE_TAG
      - cd ..
      - cd quoteservice
      - mvn package
      - docker build -t $QUOTE_IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $QUOTE_IMAGE_REPO_NAME:$IMAGE_TAG $QUOTE_ECR_URL:$IMAGE_TAG
      - cd ..
      - cd notificationservice
      - mvn package
      - docker build -t $NOTIFY_IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $NOTIFY_IMAGE_REPO_NAME:$IMAGE_TAG $NOTIFY_ECR_URL:$IMAGE_TAG
      - cd ..
      - echo "build completed"
  post_build:
    commands:
      - echo "Pushing the docker image"
      - docker push $CLAIM_ECR_URL:$IMAGE_TAG
      - docker push $POLICY_ECR_URL:$IMAGE_TAG
      - docker push $QUOTE_ECR_URL:$IMAGE_TAG
      - docker push $NOTIFY_ECR_URL:$IMAGE_TAG
      - printf '[{"name":"claims-api","imageUri":"%s"}]' $CLAIM_ECR_URL:$IMAGE_TAG > claimsimagedefinitions.json
      - printf '[{"name":"policy-api","imageUri":"%s"}]' $POLICY_ECR_URL:$IMAGE_TAG > policyimagedefinitions.json
      - printf '[{"name":"quote-api","imageUri":"%s"}]' $QUOTE_ECR_URL:$IMAGE_TAG > quoteimagedefinitions.json
      - printf '[{"name":"notify-api","imageUri":"%s"}]' $NOTIFY_ECR_URL:$IMAGE_TAG > notifyimagedefinitions.json
      - cat claimsimagedefinitions.json
      - cat policyimagedefinitions.json
      - cat quoteimagedefinitions.json
      - cat notifyimagedefinitions.json
artifacts:
    files:
      - claimsimagedefinitions.json
      - policyimagedefinitions.json
      - quoteimagedefinitions.json
      - notifyimagedefinitions.json